# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleReduxAuthGithub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleReduxAuthGithub
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRedux', :git => 'https://github.com/hungdv136/rx.redux.git'
end
